<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
      

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/Myestilo.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
           
        ?>
    </head>
    <body>
     <header>
        <img src= "<?= $this->basePath('img/LUTS.png') ?> " align="left" width="300" alt="">
        <div class="Encabezado">
          <p> Sistema de Control para  el Seguimiento de Egresados</p>
        </div>
    </header>
    <section class="centro">
        <section class= "texto">
            
        </section>
        <section class= "texto2">
          <?= $this->content ?>  
        </section>
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
    </section>

   <footer> 
    <div class="imagenes">
    <section class="imagenes">
        <ul>
            <li><img src="<?= $this->basePath('img/logo_sep.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/escudo_chiapas.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/chiapas_nos_une.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/coesmer.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/transparencia.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/ecest.png') ?>" width="150"alt=""></li>
            <li><img src="<?= $this->basePath('img/c_social.png') ?>" width="150"alt=""></li>
        </ul>
    </section>
    <section class="redes">
        <table>
            <tr>
                <td>MAPA DEL SITIO</td>
                <td><img src="<?= $this->basePath('img/twitter.png') ?>"width="50"alt="">Twitter</td>
                <td><img src="<?= $this->basePath('img/Facebook.png') ?>"width="50"alt="">Facebook</td>
        </table>
        <hr>
    </section>
    </div>

    <section class="pie">
    <p align="center" class="piedepagina">Universidad Tecnológica de la Selva <br>
    Entronque Toniná Km.0.5 Carretera Ocosingo-Altamirano,Ocosingo, Chiapas, México C.P. 29950 <br>
    Teléfonos (52)(919)673090,71,72,6731290,93</p>
    </section>
    </footer>


</body>
</html>
